package com.yl.study.model;

import java.io.Serializable;
import java.util.Date;

public class BizNode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FName
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FModuleID
     *
     * @mbg.generated
     */
    private Integer moduleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FPriority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FUniqueKey
     *
     * @mbg.generated
     */
    private String uniquekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FIsEnabled
     *
     * @mbg.generated
     */
    private Integer isenabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FEnableTime
     *
     * @mbg.generated
     */
    private Date enabletime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FOperatorName
     *
     * @mbg.generated
     */
    private String operatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FCreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FUpdateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FIsDelete
     *
     * @mbg.generated
     */
    private Integer isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FOperatorID
     *
     * @mbg.generated
     */
    private Integer operatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FModuleName
     *
     * @mbg.generated
     */
    private String modulename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Biz_Node.FModuleCode
     *
     * @mbg.generated
     */
    private String modulecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FID
     *
     * @return the value of t_Biz_Node.FID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FID
     *
     * @param id the value for t_Biz_Node.FID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FName
     *
     * @return the value of t_Biz_Node.FName
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FName
     *
     * @param name the value for t_Biz_Node.FName
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FModuleID
     *
     * @return the value of t_Biz_Node.FModuleID
     *
     * @mbg.generated
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FModuleID
     *
     * @param moduleid the value for t_Biz_Node.FModuleID
     *
     * @mbg.generated
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FPriority
     *
     * @return the value of t_Biz_Node.FPriority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FPriority
     *
     * @param priority the value for t_Biz_Node.FPriority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FUniqueKey
     *
     * @return the value of t_Biz_Node.FUniqueKey
     *
     * @mbg.generated
     */
    public String getUniquekey() {
        return uniquekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FUniqueKey
     *
     * @param uniquekey the value for t_Biz_Node.FUniqueKey
     *
     * @mbg.generated
     */
    public void setUniquekey(String uniquekey) {
        this.uniquekey = uniquekey == null ? null : uniquekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FIsEnabled
     *
     * @return the value of t_Biz_Node.FIsEnabled
     *
     * @mbg.generated
     */
    public Integer getIsenabled() {
        return isenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FIsEnabled
     *
     * @param isenabled the value for t_Biz_Node.FIsEnabled
     *
     * @mbg.generated
     */
    public void setIsenabled(Integer isenabled) {
        this.isenabled = isenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FEnableTime
     *
     * @return the value of t_Biz_Node.FEnableTime
     *
     * @mbg.generated
     */
    public Date getEnabletime() {
        return enabletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FEnableTime
     *
     * @param enabletime the value for t_Biz_Node.FEnableTime
     *
     * @mbg.generated
     */
    public void setEnabletime(Date enabletime) {
        this.enabletime = enabletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FOperatorName
     *
     * @return the value of t_Biz_Node.FOperatorName
     *
     * @mbg.generated
     */
    public String getOperatorname() {
        return operatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FOperatorName
     *
     * @param operatorname the value for t_Biz_Node.FOperatorName
     *
     * @mbg.generated
     */
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname == null ? null : operatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FCreateTime
     *
     * @return the value of t_Biz_Node.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FCreateTime
     *
     * @param createtime the value for t_Biz_Node.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FUpdateTime
     *
     * @return the value of t_Biz_Node.FUpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FUpdateTime
     *
     * @param updatetime the value for t_Biz_Node.FUpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FIsDelete
     *
     * @return the value of t_Biz_Node.FIsDelete
     *
     * @mbg.generated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FIsDelete
     *
     * @param isdelete the value for t_Biz_Node.FIsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FOperatorID
     *
     * @return the value of t_Biz_Node.FOperatorID
     *
     * @mbg.generated
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FOperatorID
     *
     * @param operatorid the value for t_Biz_Node.FOperatorID
     *
     * @mbg.generated
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FModuleName
     *
     * @return the value of t_Biz_Node.FModuleName
     *
     * @mbg.generated
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FModuleName
     *
     * @param modulename the value for t_Biz_Node.FModuleName
     *
     * @mbg.generated
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Biz_Node.FModuleCode
     *
     * @return the value of t_Biz_Node.FModuleCode
     *
     * @mbg.generated
     */
    public String getModulecode() {
        return modulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Biz_Node.FModuleCode
     *
     * @param modulecode the value for t_Biz_Node.FModuleCode
     *
     * @mbg.generated
     */
    public void setModulecode(String modulecode) {
        this.modulecode = modulecode == null ? null : modulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BizNode other = (BizNode) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getModuleid() == null ? other.getModuleid() == null : this.getModuleid().equals(other.getModuleid()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getUniquekey() == null ? other.getUniquekey() == null : this.getUniquekey().equals(other.getUniquekey()))
            && (this.getIsenabled() == null ? other.getIsenabled() == null : this.getIsenabled().equals(other.getIsenabled()))
            && (this.getEnabletime() == null ? other.getEnabletime() == null : this.getEnabletime().equals(other.getEnabletime()))
            && (this.getOperatorname() == null ? other.getOperatorname() == null : this.getOperatorname().equals(other.getOperatorname()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()))
            && (this.getOperatorid() == null ? other.getOperatorid() == null : this.getOperatorid().equals(other.getOperatorid()))
            && (this.getModulename() == null ? other.getModulename() == null : this.getModulename().equals(other.getModulename()))
            && (this.getModulecode() == null ? other.getModulecode() == null : this.getModulecode().equals(other.getModulecode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getModuleid() == null) ? 0 : getModuleid().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getUniquekey() == null) ? 0 : getUniquekey().hashCode());
        result = prime * result + ((getIsenabled() == null) ? 0 : getIsenabled().hashCode());
        result = prime * result + ((getEnabletime() == null) ? 0 : getEnabletime().hashCode());
        result = prime * result + ((getOperatorname() == null) ? 0 : getOperatorname().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        result = prime * result + ((getOperatorid() == null) ? 0 : getOperatorid().hashCode());
        result = prime * result + ((getModulename() == null) ? 0 : getModulename().hashCode());
        result = prime * result + ((getModulecode() == null) ? 0 : getModulecode().hashCode());
        return result;
    }
}