package com.yl.study.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EventDefineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public EventDefineExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Integer value) {
            addCriterion("FID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Integer value) {
            addCriterion("FID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Integer value) {
            addCriterion("FID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("FID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Integer value) {
            addCriterion("FID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Integer value) {
            addCriterion("FID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Integer> values) {
            addCriterion("FID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Integer> values) {
            addCriterion("FID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Integer value1, Integer value2) {
            addCriterion("FID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Integer value1, Integer value2) {
            addCriterion("FID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("FName is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("FName is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("FName =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("FName <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("FName >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("FName >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("FName <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("FName <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("FName like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("FName not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("FName in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("FName not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("FName between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("FName not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("FCode is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("FCode is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("FCode =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("FCode <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("FCode >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FCode >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("FCode <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("FCode <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("FCode like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("FCode not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("FCode in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("FCode not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("FCode between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("FCode not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdIsNull() {
            addCriterion("FBizDefineId is null");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdIsNotNull() {
            addCriterion("FBizDefineId is not null");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdEqualTo(Integer value) {
            addCriterion("FBizDefineId =", value, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdNotEqualTo(Integer value) {
            addCriterion("FBizDefineId <>", value, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdGreaterThan(Integer value) {
            addCriterion("FBizDefineId >", value, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FBizDefineId >=", value, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdLessThan(Integer value) {
            addCriterion("FBizDefineId <", value, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdLessThanOrEqualTo(Integer value) {
            addCriterion("FBizDefineId <=", value, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdIn(List<Integer> values) {
            addCriterion("FBizDefineId in", values, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdNotIn(List<Integer> values) {
            addCriterion("FBizDefineId not in", values, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdBetween(Integer value1, Integer value2) {
            addCriterion("FBizDefineId between", value1, value2, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FBizDefineId not between", value1, value2, "bizDefineId");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameIsNull() {
            addCriterion("FBizDefineName is null");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameIsNotNull() {
            addCriterion("FBizDefineName is not null");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameEqualTo(String value) {
            addCriterion("FBizDefineName =", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameNotEqualTo(String value) {
            addCriterion("FBizDefineName <>", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameGreaterThan(String value) {
            addCriterion("FBizDefineName >", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameGreaterThanOrEqualTo(String value) {
            addCriterion("FBizDefineName >=", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameLessThan(String value) {
            addCriterion("FBizDefineName <", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameLessThanOrEqualTo(String value) {
            addCriterion("FBizDefineName <=", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameLike(String value) {
            addCriterion("FBizDefineName like", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameNotLike(String value) {
            addCriterion("FBizDefineName not like", value, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameIn(List<String> values) {
            addCriterion("FBizDefineName in", values, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameNotIn(List<String> values) {
            addCriterion("FBizDefineName not in", values, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameBetween(String value1, String value2) {
            addCriterion("FBizDefineName between", value1, value2, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameNotBetween(String value1, String value2) {
            addCriterion("FBizDefineName not between", value1, value2, "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeIsNull() {
            addCriterion("FBizDefineCode is null");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeIsNotNull() {
            addCriterion("FBizDefineCode is not null");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeEqualTo(String value) {
            addCriterion("FBizDefineCode =", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeNotEqualTo(String value) {
            addCriterion("FBizDefineCode <>", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeGreaterThan(String value) {
            addCriterion("FBizDefineCode >", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FBizDefineCode >=", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeLessThan(String value) {
            addCriterion("FBizDefineCode <", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeLessThanOrEqualTo(String value) {
            addCriterion("FBizDefineCode <=", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeLike(String value) {
            addCriterion("FBizDefineCode like", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeNotLike(String value) {
            addCriterion("FBizDefineCode not like", value, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeIn(List<String> values) {
            addCriterion("FBizDefineCode in", values, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeNotIn(List<String> values) {
            addCriterion("FBizDefineCode not in", values, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeBetween(String value1, String value2) {
            addCriterion("FBizDefineCode between", value1, value2, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeNotBetween(String value1, String value2) {
            addCriterion("FBizDefineCode not between", value1, value2, "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdIsNull() {
            addCriterion("FNodeDefineId is null");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdIsNotNull() {
            addCriterion("FNodeDefineId is not null");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdEqualTo(Integer value) {
            addCriterion("FNodeDefineId =", value, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdNotEqualTo(Integer value) {
            addCriterion("FNodeDefineId <>", value, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdGreaterThan(Integer value) {
            addCriterion("FNodeDefineId >", value, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FNodeDefineId >=", value, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdLessThan(Integer value) {
            addCriterion("FNodeDefineId <", value, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdLessThanOrEqualTo(Integer value) {
            addCriterion("FNodeDefineId <=", value, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdIn(List<Integer> values) {
            addCriterion("FNodeDefineId in", values, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdNotIn(List<Integer> values) {
            addCriterion("FNodeDefineId not in", values, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdBetween(Integer value1, Integer value2) {
            addCriterion("FNodeDefineId between", value1, value2, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FNodeDefineId not between", value1, value2, "nodeDefineId");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameIsNull() {
            addCriterion("FNodeDefineName is null");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameIsNotNull() {
            addCriterion("FNodeDefineName is not null");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameEqualTo(String value) {
            addCriterion("FNodeDefineName =", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameNotEqualTo(String value) {
            addCriterion("FNodeDefineName <>", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameGreaterThan(String value) {
            addCriterion("FNodeDefineName >", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameGreaterThanOrEqualTo(String value) {
            addCriterion("FNodeDefineName >=", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameLessThan(String value) {
            addCriterion("FNodeDefineName <", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameLessThanOrEqualTo(String value) {
            addCriterion("FNodeDefineName <=", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameLike(String value) {
            addCriterion("FNodeDefineName like", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameNotLike(String value) {
            addCriterion("FNodeDefineName not like", value, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameIn(List<String> values) {
            addCriterion("FNodeDefineName in", values, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameNotIn(List<String> values) {
            addCriterion("FNodeDefineName not in", values, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameBetween(String value1, String value2) {
            addCriterion("FNodeDefineName between", value1, value2, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameNotBetween(String value1, String value2) {
            addCriterion("FNodeDefineName not between", value1, value2, "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeIsNull() {
            addCriterion("FNodeDefineCode is null");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeIsNotNull() {
            addCriterion("FNodeDefineCode is not null");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeEqualTo(String value) {
            addCriterion("FNodeDefineCode =", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeNotEqualTo(String value) {
            addCriterion("FNodeDefineCode <>", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeGreaterThan(String value) {
            addCriterion("FNodeDefineCode >", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FNodeDefineCode >=", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeLessThan(String value) {
            addCriterion("FNodeDefineCode <", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeLessThanOrEqualTo(String value) {
            addCriterion("FNodeDefineCode <=", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeLike(String value) {
            addCriterion("FNodeDefineCode like", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeNotLike(String value) {
            addCriterion("FNodeDefineCode not like", value, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeIn(List<String> values) {
            addCriterion("FNodeDefineCode in", values, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeNotIn(List<String> values) {
            addCriterion("FNodeDefineCode not in", values, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeBetween(String value1, String value2) {
            addCriterion("FNodeDefineCode between", value1, value2, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeNotBetween(String value1, String value2) {
            addCriterion("FNodeDefineCode not between", value1, value2, "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andTopicIsNull() {
            addCriterion("FTopic is null");
            return (Criteria) this;
        }

        public Criteria andTopicIsNotNull() {
            addCriterion("FTopic is not null");
            return (Criteria) this;
        }

        public Criteria andTopicEqualTo(String value) {
            addCriterion("FTopic =", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotEqualTo(String value) {
            addCriterion("FTopic <>", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicGreaterThan(String value) {
            addCriterion("FTopic >", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicGreaterThanOrEqualTo(String value) {
            addCriterion("FTopic >=", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLessThan(String value) {
            addCriterion("FTopic <", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLessThanOrEqualTo(String value) {
            addCriterion("FTopic <=", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLike(String value) {
            addCriterion("FTopic like", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotLike(String value) {
            addCriterion("FTopic not like", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicIn(List<String> values) {
            addCriterion("FTopic in", values, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotIn(List<String> values) {
            addCriterion("FTopic not in", values, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicBetween(String value1, String value2) {
            addCriterion("FTopic between", value1, value2, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotBetween(String value1, String value2) {
            addCriterion("FTopic not between", value1, value2, "topic");
            return (Criteria) this;
        }

        public Criteria andSubscribeIsNull() {
            addCriterion("FSubscribe is null");
            return (Criteria) this;
        }

        public Criteria andSubscribeIsNotNull() {
            addCriterion("FSubscribe is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribeEqualTo(String value) {
            addCriterion("FSubscribe =", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeNotEqualTo(String value) {
            addCriterion("FSubscribe <>", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeGreaterThan(String value) {
            addCriterion("FSubscribe >", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeGreaterThanOrEqualTo(String value) {
            addCriterion("FSubscribe >=", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeLessThan(String value) {
            addCriterion("FSubscribe <", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeLessThanOrEqualTo(String value) {
            addCriterion("FSubscribe <=", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeLike(String value) {
            addCriterion("FSubscribe like", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeNotLike(String value) {
            addCriterion("FSubscribe not like", value, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeIn(List<String> values) {
            addCriterion("FSubscribe in", values, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeNotIn(List<String> values) {
            addCriterion("FSubscribe not in", values, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeBetween(String value1, String value2) {
            addCriterion("FSubscribe between", value1, value2, "subscribe");
            return (Criteria) this;
        }

        public Criteria andSubscribeNotBetween(String value1, String value2) {
            addCriterion("FSubscribe not between", value1, value2, "subscribe");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameIsNull() {
            addCriterion("FProducerGroupName is null");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameIsNotNull() {
            addCriterion("FProducerGroupName is not null");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameEqualTo(String value) {
            addCriterion("FProducerGroupName =", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameNotEqualTo(String value) {
            addCriterion("FProducerGroupName <>", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameGreaterThan(String value) {
            addCriterion("FProducerGroupName >", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("FProducerGroupName >=", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameLessThan(String value) {
            addCriterion("FProducerGroupName <", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameLessThanOrEqualTo(String value) {
            addCriterion("FProducerGroupName <=", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameLike(String value) {
            addCriterion("FProducerGroupName like", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameNotLike(String value) {
            addCriterion("FProducerGroupName not like", value, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameIn(List<String> values) {
            addCriterion("FProducerGroupName in", values, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameNotIn(List<String> values) {
            addCriterion("FProducerGroupName not in", values, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameBetween(String value1, String value2) {
            addCriterion("FProducerGroupName between", value1, value2, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameNotBetween(String value1, String value2) {
            addCriterion("FProducerGroupName not between", value1, value2, "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameIsNull() {
            addCriterion("FConsumerGroupName is null");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameIsNotNull() {
            addCriterion("FConsumerGroupName is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameEqualTo(String value) {
            addCriterion("FConsumerGroupName =", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameNotEqualTo(String value) {
            addCriterion("FConsumerGroupName <>", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameGreaterThan(String value) {
            addCriterion("FConsumerGroupName >", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("FConsumerGroupName >=", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameLessThan(String value) {
            addCriterion("FConsumerGroupName <", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameLessThanOrEqualTo(String value) {
            addCriterion("FConsumerGroupName <=", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameLike(String value) {
            addCriterion("FConsumerGroupName like", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameNotLike(String value) {
            addCriterion("FConsumerGroupName not like", value, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameIn(List<String> values) {
            addCriterion("FConsumerGroupName in", values, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameNotIn(List<String> values) {
            addCriterion("FConsumerGroupName not in", values, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameBetween(String value1, String value2) {
            addCriterion("FConsumerGroupName between", value1, value2, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameNotBetween(String value1, String value2) {
            addCriterion("FConsumerGroupName not between", value1, value2, "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNull() {
            addCriterion("FIsEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNotNull() {
            addCriterion("FIsEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledEqualTo(Integer value) {
            addCriterion("FIsEnabled =", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotEqualTo(Integer value) {
            addCriterion("FIsEnabled <>", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThan(Integer value) {
            addCriterion("FIsEnabled >", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThanOrEqualTo(Integer value) {
            addCriterion("FIsEnabled >=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThan(Integer value) {
            addCriterion("FIsEnabled <", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThanOrEqualTo(Integer value) {
            addCriterion("FIsEnabled <=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIn(List<Integer> values) {
            addCriterion("FIsEnabled in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotIn(List<Integer> values) {
            addCriterion("FIsEnabled not in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledBetween(Integer value1, Integer value2) {
            addCriterion("FIsEnabled between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotBetween(Integer value1, Integer value2) {
            addCriterion("FIsEnabled not between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andStepIsNull() {
            addCriterion("FStep is null");
            return (Criteria) this;
        }

        public Criteria andStepIsNotNull() {
            addCriterion("FStep is not null");
            return (Criteria) this;
        }

        public Criteria andStepEqualTo(Integer value) {
            addCriterion("FStep =", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotEqualTo(Integer value) {
            addCriterion("FStep <>", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThan(Integer value) {
            addCriterion("FStep >", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("FStep >=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThan(Integer value) {
            addCriterion("FStep <", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThanOrEqualTo(Integer value) {
            addCriterion("FStep <=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepIn(List<Integer> values) {
            addCriterion("FStep in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotIn(List<Integer> values) {
            addCriterion("FStep not in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepBetween(Integer value1, Integer value2) {
            addCriterion("FStep between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotBetween(Integer value1, Integer value2) {
            addCriterion("FStep not between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andDelayTypeIsNull() {
            addCriterion("FDelayType is null");
            return (Criteria) this;
        }

        public Criteria andDelayTypeIsNotNull() {
            addCriterion("FDelayType is not null");
            return (Criteria) this;
        }

        public Criteria andDelayTypeEqualTo(Integer value) {
            addCriterion("FDelayType =", value, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeNotEqualTo(Integer value) {
            addCriterion("FDelayType <>", value, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeGreaterThan(Integer value) {
            addCriterion("FDelayType >", value, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FDelayType >=", value, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeLessThan(Integer value) {
            addCriterion("FDelayType <", value, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("FDelayType <=", value, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeIn(List<Integer> values) {
            addCriterion("FDelayType in", values, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeNotIn(List<Integer> values) {
            addCriterion("FDelayType not in", values, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeBetween(Integer value1, Integer value2) {
            addCriterion("FDelayType between", value1, value2, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("FDelayType not between", value1, value2, "delayType");
            return (Criteria) this;
        }

        public Criteria andDelayLevelIsNull() {
            addCriterion("FDelayLevel is null");
            return (Criteria) this;
        }

        public Criteria andDelayLevelIsNotNull() {
            addCriterion("FDelayLevel is not null");
            return (Criteria) this;
        }

        public Criteria andDelayLevelEqualTo(Integer value) {
            addCriterion("FDelayLevel =", value, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelNotEqualTo(Integer value) {
            addCriterion("FDelayLevel <>", value, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelGreaterThan(Integer value) {
            addCriterion("FDelayLevel >", value, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("FDelayLevel >=", value, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelLessThan(Integer value) {
            addCriterion("FDelayLevel <", value, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelLessThanOrEqualTo(Integer value) {
            addCriterion("FDelayLevel <=", value, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelIn(List<Integer> values) {
            addCriterion("FDelayLevel in", values, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelNotIn(List<Integer> values) {
            addCriterion("FDelayLevel not in", values, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelBetween(Integer value1, Integer value2) {
            addCriterion("FDelayLevel between", value1, value2, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("FDelayLevel not between", value1, value2, "delayLevel");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeIsNull() {
            addCriterion("FDelayCalculatorCode is null");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeIsNotNull() {
            addCriterion("FDelayCalculatorCode is not null");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeEqualTo(String value) {
            addCriterion("FDelayCalculatorCode =", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeNotEqualTo(String value) {
            addCriterion("FDelayCalculatorCode <>", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeGreaterThan(String value) {
            addCriterion("FDelayCalculatorCode >", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FDelayCalculatorCode >=", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeLessThan(String value) {
            addCriterion("FDelayCalculatorCode <", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeLessThanOrEqualTo(String value) {
            addCriterion("FDelayCalculatorCode <=", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeLike(String value) {
            addCriterion("FDelayCalculatorCode like", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeNotLike(String value) {
            addCriterion("FDelayCalculatorCode not like", value, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeIn(List<String> values) {
            addCriterion("FDelayCalculatorCode in", values, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeNotIn(List<String> values) {
            addCriterion("FDelayCalculatorCode not in", values, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeBetween(String value1, String value2) {
            addCriterion("FDelayCalculatorCode between", value1, value2, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeNotBetween(String value1, String value2) {
            addCriterion("FDelayCalculatorCode not between", value1, value2, "delayCalculatorCode");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("FLastModifyTime is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("FLastModifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("FLastModifyTime =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("FLastModifyTime <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("FLastModifyTime >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FLastModifyTime >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("FLastModifyTime <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("FLastModifyTime <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("FLastModifyTime in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("FLastModifyTime not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("FLastModifyTime between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("FLastModifyTime not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andRetryIsNull() {
            addCriterion("FRetry is null");
            return (Criteria) this;
        }

        public Criteria andRetryIsNotNull() {
            addCriterion("FRetry is not null");
            return (Criteria) this;
        }

        public Criteria andRetryEqualTo(Integer value) {
            addCriterion("FRetry =", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryNotEqualTo(Integer value) {
            addCriterion("FRetry <>", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryGreaterThan(Integer value) {
            addCriterion("FRetry >", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryGreaterThanOrEqualTo(Integer value) {
            addCriterion("FRetry >=", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryLessThan(Integer value) {
            addCriterion("FRetry <", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryLessThanOrEqualTo(Integer value) {
            addCriterion("FRetry <=", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryIn(List<Integer> values) {
            addCriterion("FRetry in", values, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryNotIn(List<Integer> values) {
            addCriterion("FRetry not in", values, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryBetween(Integer value1, Integer value2) {
            addCriterion("FRetry between", value1, value2, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryNotBetween(Integer value1, Integer value2) {
            addCriterion("FRetry not between", value1, value2, "retry");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(FName) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(FCode) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andBizDefineNameLikeInsensitive(String value) {
            addCriterion("upper(FBizDefineName) like", value.toUpperCase(), "bizDefineName");
            return (Criteria) this;
        }

        public Criteria andBizDefineCodeLikeInsensitive(String value) {
            addCriterion("upper(FBizDefineCode) like", value.toUpperCase(), "bizDefineCode");
            return (Criteria) this;
        }

        public Criteria andNodeDefineNameLikeInsensitive(String value) {
            addCriterion("upper(FNodeDefineName) like", value.toUpperCase(), "nodeDefineName");
            return (Criteria) this;
        }

        public Criteria andNodeDefineCodeLikeInsensitive(String value) {
            addCriterion("upper(FNodeDefineCode) like", value.toUpperCase(), "nodeDefineCode");
            return (Criteria) this;
        }

        public Criteria andTopicLikeInsensitive(String value) {
            addCriterion("upper(FTopic) like", value.toUpperCase(), "topic");
            return (Criteria) this;
        }

        public Criteria andSubscribeLikeInsensitive(String value) {
            addCriterion("upper(FSubscribe) like", value.toUpperCase(), "subscribe");
            return (Criteria) this;
        }

        public Criteria andProducerGroupNameLikeInsensitive(String value) {
            addCriterion("upper(FProducerGroupName) like", value.toUpperCase(), "producerGroupName");
            return (Criteria) this;
        }

        public Criteria andConsumerGroupNameLikeInsensitive(String value) {
            addCriterion("upper(FConsumerGroupName) like", value.toUpperCase(), "consumerGroupName");
            return (Criteria) this;
        }

        public Criteria andDelayCalculatorCodeLikeInsensitive(String value) {
            addCriterion("upper(FDelayCalculatorCode) like", value.toUpperCase(), "delayCalculatorCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Evt_EventDefine
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}