package com.yl.study.mapper;

import com.yl.study.model.BizNode;
import com.yl.study.model.BizNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    long countByExample(BizNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int deleteByExample(BizNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int insert(BizNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int insertSelective(BizNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    List<BizNode> selectByExample(BizNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    BizNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BizNode record, @Param("example") BizNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BizNode record, @Param("example") BizNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BizNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Biz_Node
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BizNode record);
}